### ISSUE TITLE
Add sound

### ISSUE THREAD

**Issue by mediapinta** [samueljun/Pomodoro-Clock#5]
Hi
It would be possible to add sound? I like minimal add-ons, but I'm not looking to my computer all the time.

Thanks.

ifrit

**Comment by samueljun** [comment]
I could see a longer more distinct alarm sound rather than the default Firefox notification sound. Is that what you have in mind?

**Comment by mediapinta** [comment]
Ok. So, there is actually a sound and I'm not hearing it... My problem, sorry :p (Lubuntu 14.10, Firefox 39.0)

**Comment by samueljun** [comment]
If you're happy I'm happy. Closing this issue :)
